# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('fechacomment', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('idpost', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_post', models.CharField(max_length=300)),
                ('Informacion', models.CharField(max_length=200)),
                ('Foto_post', models.ImageField(upload_to='foto_post')),
                ('Fecha_post', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Categoria', models.CharField(choices=[('Salud', 'Salud'), ('Servicio_comunitario', 'Servicio_comunitario'), ('Educacion', 'Educacion')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('fecharespuesta', models.DateTimeField()),
                ('idcomentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='sigue',
            fields=[
                ('idsigue', models.AutoField(primary_key=True, serialize=False)),
                ('idpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_paterno', models.CharField(max_length=50)),
                ('Apellido_materno', models.CharField(max_length=50)),
                ('Genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=30)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(max_length=50)),
                ('No_telefono', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Biografia', models.CharField(max_length=300)),
                ('Tipo_usuario', models.CharField(choices=[('Institucion', 'Instituci\xf3n'), ('Persona', 'Persona')], max_length=30)),
                ('Foto_de_perfil', models.ImageField(upload_to='foto_perfil')),
                ('iduser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sigue',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='post',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
