# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Foto_post',
            field=models.ImageField(blank=True, null=True, upload_to='foto_post'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Foto_de_perfil',
            field=models.ImageField(default='foto_post/diadoumenos_head_167x197.jpg', upload_to='foto_perfil'),
        ),
    ]
